include: package:flutter_lints/flutter.yaml

analyzer:
  strong-mode:
    implicit-casts: false
    implicit-dynamic: false

  errors:
    # Turn important lint rules into errors:
    always_use_package_imports: error
    avoid_print: error
    prefer_const_constructors: error
    prefer_const_literals_to_create_immutables: error
    prefer_const_declarations: error
    use_key_in_widget_constructors: error
    no_duplicate_case_values: error
    invalid_use_of_visible_for_testing_member: error
    unnecessary_nullable_for_final_variable_declarations: error

linter:
  rules:
    # ------------------------------
    # STYLE & CLEAN CODE RULES
    # ------------------------------
    always_declare_return_types: true
    always_put_required_named_parameters_first: true
    avoid_dynamic_calls: true
    avoid_function_literals_in_foreach_calls: true
    avoid_shadowing_type_parameters: true
    avoid_null_checks_in_equality_operators: true
    avoid_unnecessary_containers: true
    avoid_print: true
    avoid_type_to_string: true
    prefer_final_locals: true
    prefer_final_fields: true
    prefer_mixin: true
    unnecessary_getters_setters: true
    unnecessary_lambdas: true
    unnecessary_parenthesis: true

    # ------------------------------
    # CONST OPTIMIZATION RULES
    # ------------------------------
    prefer_const_constructors: true
    prefer_const_literals_to_create_immutables: true
    prefer_const_declarations: true

    # ------------------------------
    # NAMING RULES
    # ------------------------------
    camel_case_types: true
    camel_case_extensions: true
    file_names: true

    # ------------------------------
    # IMPORT RULES
    # ------------------------------
    always_use_package_imports: true
    directives_ordering: true
    sort_pub_dependencies: true

    # ------------------------------
    # FLUTTER SPECIFIC RULES
    # ------------------------------
    use_key_in_widget_constructors: true
    prefer_single_widget_per_file: false  # set to true if you prefer

    # ------------------------------
    # SAFETY RULES
    # ------------------------------
    close_sinks: true
    cancel_subscriptions: true
    avoid_catches_without_on_clauses: true
    avoid_empty_else: true
    unawaited_futures: true

    # ------------------------------
    # PERFORMANCE
    # ------------------------------
    unnecessary_await_in_return: true
    unnecessary_this: true
    await_only_futures: true
    avoid_unnecessary_async: true
